INSERT INTO jeuxvideo (idjeux, idtype, idmode, nomdujeux, datesortie, editeur, prixlancement, restriction_age, tailledujeux, idconf_min, idconf_max) VALUES (3, 4, 1, 'Resident evil 7', '2017-01-24', 'Capcom', 30, 18, 15, 2, 1);


INSERT INTO mode_de_jeux (idmode, libelle) VALUES (1, 'Solo');
INSERT INTO mode_de_jeux (idmode, libelle) VALUES (2, 'Multi');



INSERT INTO plateforme_de_jeux (idplateforme, libelle) VALUES (1, 'Xbox 360');
INSERT INTO plateforme_de_jeux (idplateforme, libelle) VALUES (2, 'PS3');
INSERT INTO plateforme_de_jeux (idplateforme, libelle) VALUES (3, 'PS4');
INSERT INTO plateforme_de_jeux (idplateforme, libelle) VALUES (4, 'PS4 Pro');
INSERT INTO plateforme_de_jeux (idplateforme, libelle) VALUES (5, 'Xbox One');
INSERT INTO plateforme_de_jeux (idplateforme, libelle) VALUES (6, 'PC');
INSERT INTO plateforme_de_jeux (idplateforme, libelle) VALUES (7, 'Mac');
INSERT INTO plateforme_de_jeux (idplateforme, libelle) VALUES (8, 'Android');
INSERT INTO plateforme_de_jeux (idplateforme, libelle) VALUES (9, 'Ios');
INSERT INTO plateforme_de_jeux (idplateforme, libelle) VALUES (10, 'Switch');

INSERT INTO typejeux (idtype, libelle, apropos) VALUES (1, 'Action', 'Tout jeu faisant appel de la part du joueur à une mise à l''épreuve de ses réflexes et de son habileté à diriger l''avancement de la partie à travers le temps et l''espace du jeu correspond à un jeu d''action. Ce type de jeu est très ancien, puisque le tout premier jeu vidéo connu à avoir été créé en 1947, appelé dispositif de jeu à tube cathodique, est un jeu d''action. Les jeux d''actions constituent une très vaste catégorie du jeu vidéo qui regroupe des titres aussi divers que variés, eux-mêmes classifiés en plusieurs sous-catégories.');
INSERT INTO typejeux (idtype, libelle, apropos) VALUES (2, 'Le Beat-Them-All', 'Le joueur incarne un personnage et il progresse via un scrolling vertical ou horizontal le plus souvent. Le joueur peut récupérer des armes, bonus, utiliser des coups de poings ou de pieds, voire même des coups spéciaux. Des jeux comme Final Fight ou plus récemment GunGrave sont un bon exemple. Ce type de jeux a connu son heure de gloire dans les années 1985-1995. ');
INSERT INTO typejeux (idtype, libelle, apropos) VALUES (3, 'Le Beat-Them-up', 'c’est le jeu de baston classique, en 2D (King of Fighters, Street Fighter, Marvel Vs Capcom) ou 3D (Dead or Alive ,SoulCalibur, Tekken, Virtua Fighter). Le joueur choisi son personnage et doit affronter un à un les autres personnages du jeu. Selon les cas, le combat est à mains nues ou à l’aide d’armes. Très prisé en arcade dans les années 1992-2000 (lorsque l’écart technique entre arcade et consoles était encore énorme), ces jeux ont entamé une nouvelle carrière sur les consoles nouvelle génération, où ils peuvent exprimer leur potentiel. Du coup, en arcade ce genre est peu à peu délaissé. ');
INSERT INTO typejeux (idtype, libelle, apropos) VALUES (4, 'Le Survival – Horror', 'Ce sous-style a été initié par des jeux comme Alone In The Dark, puis avec l’arrivée de la Playstation, il s’est imposé à travers des licences phares comme Resident Evil (Biohasard), Silent Hill ou encore Project Zero…
Le but c’est de faire vivre au joueur des sentiments comme la peur et l’angoisse. L’accent est mis sur l’ambiance graphique certes, mais surtout sonore, plongeant le joueur plus avant dans l’univers sombre de l’histoire… ');
INSERT INTO typejeux (idtype, libelle, apropos) VALUES (5, 'Plates-formes', 'Le joueur incarne un personnage et il doit le faire avancer dans la partie, en le faisant sauter de plateforme en plate-forme. Les exemples type ce sont des jeux comme Mario ou Sonic. A l’époque des consoles 8 et 16 bits, ces jeux étaient très répandus dans leur forme basique, avec un scrolling vertical ou horizontal.
Le plus souvent il fallait parcourir un niveau d’un point A vers un point B en évitant les pièges ou en tuant les ennemis à l’écran… Mais de plus en plus et surtout avec l’arrivée des technologies modernes et des jeux en 3D temps réel, ces jeux de plateforme se complexifient, intégrant une bonne dose d’aventure ou d’action ou encore du tir.
Sans parler de l’aspect 3D qui donne au joueur de nouvelles possibilités de jeu, mais aussi une autre approche en termes de jouabilité. Par exemple, un jeu comme Ratchet & Clank mélange bien plusieurs styles de jeux et en ce sens il est représentatif de la nouvelle tendance. ');
INSERT INTO typejeux (idtype, libelle, apropos) VALUES (6, 'simulation mécanique', 'Course de voitures, pilotage d’avions, etc.(Flight Simulator, Colin Mac Rae, MS Train Simulator, Virtual Skipper, Revolt, Silent Hunter...). 
L’usure, les dégâts, le temps, les caractéristiques physiques, voilà des exemples de paramètres qui entrent en scène dans ce style de jeux. ');
INSERT INTO typejeux (idtype, libelle, apropos) VALUES (7, 'simulation sportive', 'On incarne un sportif ou une équipe de sportifs et on doit gagner contre un autre joueur ou contre le programme. La notion de temps est essentielle pour accéder à la victoire. Ces jeux sont souvent basés sur des licences (noms d’équipes, de joueurs, de championnats, etc.), et ils collent au règlement officiel du sport en question. Ce sont des jeux très répandus. Des sociétés comme Electronic Arts étant des spécialistes dans l’élaboration de ce type de contenu. ');
INSERT INTO typejeux (idtype, libelle, apropos) VALUES (8, 'Tir', 'Un jeu de tir est un jeu d''action qui demande au joueur d''être capable, à partir du personnage/véhicule qu''il contrôle, de tirer sur les adversaires qui parsèment les niveaux avec sa ou ses armes/pouvoirs/projectiles pour les neutraliser. Le joueur devra également veiller à se déplacer suffisamment rapidement pour se mettre à couvert ou éviter les tirs ou attaques au corps à corps de ses ennemis.');
INSERT INTO typejeux (idtype, libelle, apropos) VALUES (9, 'FPS', 'Les jeux de tir à la première personne (ou FPS pour First-Person Shooter) sont basés sur une visée et des déplacements à la première personne. Cette perspective a pour but de donner l''impression au joueur « d''être là », à la place du personnage tenant l''arme et voyant exactement ce qu''il voit, générant ainsi une forte identification accentuée par des graphismes en trois dimensions. Le gameplay est de manière générale rapide et requiert de bons réflexes. Si les FPS sont des jeux de tir, il est à noter que toutes les armes utilisées ne le sont pas forcément : il peut s''agir d''armes de corps à corps tel que des couteaux, des pieds de biche ou des sabres lasers, bien que ces derniers ne constituent qu''une petite partie de l''arsenal qui lui est très souvent plus orienté vers les armes de tirs.');
INSERT INTO typejeux (idtype, libelle, apropos) VALUES (10, 'Tir en vue objective(TPS)', 'Les jeux de tir à la troisième personne, ou tir objectif (ou TPS pour Third-Person Shooter) sont similaires aux jeux de tir à la première personne à la différence que le personnage est vu de dos et parfois avec une perspective isométrique. Le joueur a une vision élargie de l''environnement et sa liberté de mouvement est accrue. Resident Evil 4 et Resident Evil 5 sont des mélanges de TPS et de Survival-Horror');

